version: '3.6'

volumes:
  postgres_data:

services:
  postgres:
    image: postgres:11.6-alpine
    environment:
      POSTGRES_DB: gundonis
      POSTGRES_USER: gundonis
      POSTGRES_PASSWORD: gundonis
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
